apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-hello-app-tls
spec:
  secretName: nginx-hello-app-tls
  usages:
  - "digital signature"
  - "key encipherment"
  dnsNames:
  - "nginx-hello.example.com"
  - "nginx-echo.example.com"
  issuerRef:
    name: akley-common-issuer
    kind: ClusterIssuer