nginx:
  kind: deployment
  replicas: 1
  image:
    repository: ghcr.io/nginx/nginx-gateway-fabric/nginx
    tag: 2.3.0
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    nodePorts:
    - port: 30000
      listenerPort: 80
    - port: 30001
      listenerPort: 443